### ISSUE TITLE
Youtube videos no longer play.

### ISSUE THREAD

**Issue by simakuutio** [Leshuguita/PotPlayer-SponsorBlock#2]
Recently youtube changed something and videos can't be opened with PotPlayer anymore. 
Using most recent PotPlayer and most recent version of PotPlayer-SponsorBlock.
(reported here because fork  version for some reason doesn't have an option to open issue).

**Comment by eldepor** [comment]
@Alexey71

**Comment by eldepor** [comment]
Tienes que volver Leshuguita, poder ver YT en potplayer es imprescindible :,((

**Comment by Alexey71** [comment]
Also original MediaPlayParse - YouTube.as for potplayer not working. Something has changed on YouTube. There is no solution yet. Wait for the potplayer developer to fix it

**Comment by eldepor** [comment]
Maybe the problem is android player api json request

**Comment by eldepor** [comment]
~~@Alexey71 Potplayer developers have not updated the script for YEARS, you had the most updated one, in fact, thanks to your last update 3 months ago we were able to play livestreams from YT.~~

But anyway I kind of fixed it. Use ios client instead of android in GetVideoJson:

~~Edit: this one is returning AV1 format videos, changing user agent, device model and yt version return different formats. If you want vp9 format HW accel use [android vr version](https://github.com/Leshuguita/PotPlayer-SponsorBlock/issues/2#issuecomment-2495555783) but livestreams not working~~

Edit2: you can use [android vr](https://github.com/Leshuguita/PotPlayer-SponsorBlock/issues/2#issuecomment-2495555783) client too

```
string GetVideoJson(string videoId, bool passAge)
{
	string Headers = "X-YouTube-Client-Name: 5\r\nX-YouTube-Client-Version: 19.45.4\r\nOrigin: https://www.youtube.com\r\ncontent-type: application/json\r\n";
	string postData = "{\"contentCheckOk\": true, \"context\": {\"client\": {\"clientName\": \"IOS\", \"clientVersion\": \"19.45.4\", "
				"\"deviceMake\": \"Apple\", \"deviceModel\": \"iPhone16,2\", \"hl\": \"" + HostIso639LangName() + "\", \"osName\": \"iPhone\", \"osVersion\": \"18.1.0.22B83\", "
				"\"timeZone\": \"UTC\", \"utcOffsetMinutes\": 0}}, \"playbackContext\": {\"contentPlaybackContext\": {\"html5Preference\": \"HTML5_PREF_WANTS\"}}, \"racyCheckOk\" : true, \"videoId\" : \"" + videoId + "\"}";
	string postData2 = "{\"context\": {\"client\": {\"clientName\": \"IOS\", \"clientVersion\": \"19.45.4\", \"clientScreen\": \"EMBED\"}, \"thirdParty\": {\"embedUrl\": \"https://google.com\"}}, \"videoId\": \"" + videoId + "\", \"params\": \"wgYCCAA=\", \"contentCheckOk\": true, \"racyCheckOk\": true}";
	
	return HostUrlGetStringWithAPI("https://www.youtube.com/youtubei/v1/player", "com.google.ios.youtube/19.45.4 (iPhone16,2; U; CPU iOS 18_1_0 like Mac OS X;)", Headers, passAge ? postData2 : postData, true);
}

````

**Comment by Alexey71** [comment]
> @Alexey71 Potplayer developers have not updated the script for YEARS, in fact, thanks to your last update 3 months ago we were able to play livestreams from YT.
> 
> But anyway I kind of fixed it. Use ios client instead of android in GetVideoJson:
> 
> ```
> string GetVideoJson(string videoId, bool passAge)
> {
> 	string Headers = "X-YouTube-Client-Name: 5\r\nX-YouTube-Client-Version: 19.45.4\r\nOrigin: https://www.youtube.com\r\ncontent-type: application/json\r\n";
> 	string postData = "{\"context\": {\"client\": {\"clientName\": \"IOS\", \"clientVersion\": \"19.45.4\", \"hl\": \"" + HostIso639LangName() + "\"}}, \"videoId\": \"" + videoId + "\", \"params\": \"wgYCCAA=\", \"playbackContext\": {\"contentPlaybackContext\": {\"html5Preference\": \"HTML5_PREF_WANTS\"}}, \"contentCheckOk\": true, \"racyCheckOk\": true}";
> 	string postData2 = "{\"context\": {\"client\": {\"clientName\": \"IOS\", \"clientVersion\": \"19.45.4\", \"clientScreen\": \"EMBED\"}, \"thirdParty\": {\"embedUrl\": \"https://google.com\"}}, \"videoId\": \"" + videoId + "\", \"params\": \"wgYCCAA=\", \"contentCheckOk\": true, \"racyCheckOk\": true}";
> 	
> 	return HostUrlGetStringWithAPI("https://www.youtube.com/youtubei/v1/player", "com.google.ios.youtube/19.45.4 (iPhone16,2; U; CPU iOS 18_1_0 like Mac OS X;)", Headers, passAge ? postData2 : postData, true);
> }
> ```

Not working for me

**Comment by eldepor** [comment]
> Not working for me

Reload the extension in potplayer. Or try this one, Android VR client 

```
string GetVideoJson(string videoId, bool passAge)
{
	string Headers = "X-YouTube-Client-Name: 28\r\nX-YouTube-Client-Version: 1.60.19\r\nOrigin: https://www.youtube.com\r\ncontent-type: application/json\r\n";
	string postData = "{\"context\": {\"client\": {\"clientName\": \"ANDROID_VR\", \"clientVersion\": \"1.60.19\", \"deviceMake\": \"Oculus\", \"deviceModel\": \"Quest 3\", \"hl\": \"" + HostIso639LangName() + "\"}}, \"videoId\": \"" + videoId + "\", \"params\": \"wgYCCAA=\", \"playbackContext\": {\"contentPlaybackContext\": {\"html5Preference\": \"HTML5_PREF_WANTS\"}}, \"contentCheckOk\": true, \"racyCheckOk\": true}";
	string postData2 = "{\"context\": {\"client\": {\"clientName\": \"ANDROID_VR\", \"clientVersion\": \"1.60.19\", \"deviceMake\": \"Oculus\", \"deviceModel\": \"Quest 3\", \"clientScreen\": \"EMBED\"}, \"thirdParty\": {\"embedUrl\": \"https://google.com\"}}, \"videoId\": \"" + videoId + "\", \"params\": \"wgYCCAA=\", \"contentCheckOk\": true, \"racyCheckOk\": true}";
	
	return HostUrlGetStringWithAPI("https://www.youtube.com/youtubei/v1/player", "com.google.android.apps.youtube.vr.oculus/1.60.19 (Linux; U; Android 12L; eureka-user Build/SQ3A.220605.009.A1) gzip", Headers, passAge ? postData2 : postData, true);
}
```

**Comment by Alexey71** [comment]
> Reload the extension in potplayer

Oh thx, Now fine

**Comment by eldepor** [comment]
~~One thing, I noticed live streams not working, so we need a fix for that.
Another thing, with that ios user agent and device version the script returns av1 format videos, if someone wants vp9 or higher resolutions in avc must use android vr client. Live streams not working either.~~

**Comment by Alexey71** [comment]
> One thing, I noticed live streams not working, so we need a fix for that.

Hm. I tried and working, test link https://www.youtube.com/watch?v=eoaWlLWW5U0&pp=ygULbGl2ZSBzdHJlYW0%3D

https://www.youtube.com/watch?v=Q8MR7grOuuA&pp=ygULbGl2ZSBzdHJlYW0%3D

![изображение](https://github.com/user-attachments/assets/199e6b1b-6b3b-428f-92b6-ae4666ec2459)

**Comment by eldepor** [comment]
> > One thing, I noticed live streams not working, so we need a fix for that.
> 
> Hm. I tried and working, test link https://www.youtube.com/watch?v=eoaWlLWW5U0&pp=ygULbGl2ZSBzdHJlYW0%3D
> 
> https://www.youtube.com/watch?v=Q8MR7grOuuA&pp=ygULbGl2ZSBzdHJlYW0%3D
> 
> ![изображение](https://private-user-images.githubusercontent.com/10572914/389217831-199e6b1b-6b3b-428f-92b6-ae4666ec2459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODY2NjcsIm5iZiI6MTczMjM4NjM2NywicGF0aCI6Ii8xMDU3MjkxNC8zODkyMTc4MzEtMTk5ZTZiMWItNmIzYi00MjhmLTkyYjYtYWU0NjY2ZWMyNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE4MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkN2YyNTY2MWU3MmViZWY3ZDgwNWM2MmQ2NTgxODkxYzI2OTNkMjg5M2Q0ZmQzNDI2MWMwNzM4ZDVlMzMwMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Le4WHWu-GclNg5RLzMn7uiu4A1GQA6UK2xULq_M5Rs)

True, my bad. I was using strange parameter in the url. Thx.

**Comment by eldepor** [comment]
> > One thing, I noticed live streams not working, so we need a fix for that.
> 
> Hm. I tried and working, test link https://www.youtube.com/watch?v=eoaWlLWW5U0&pp=ygULbGl2ZSBzdHJlYW0%3D
> 
> https://www.youtube.com/watch?v=Q8MR7grOuuA&pp=ygULbGl2ZSBzdHJlYW0%3D
> 


True, my bad. I was using strange parameter in the url. Thx.

**Comment by eldepor** [comment]
~~Also, for hardware acceleration use android_vr one~~

Edit: modified [ios client](https://github.com/Leshuguita/PotPlayer-SponsorBlock/issues/2#issuecomment-2495543046) parameters to return HW acc formats. But to get 8k use [android_vr](https://github.com/Leshuguita/PotPlayer-SponsorBlock/issues/2#issuecomment-2495555783)
